version: '2'
services:
  workspace:
    image: 925336818186.dkr.ecr.eu-west-2.amazonaws.com/workspace:v6
    mem_limit: 200000000
    container_name: app_workspace
    tty: true
    command: 'tail -f /dev/null'
    ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
        - "3003:3003"
    volumes:
       - /home/ec2-user/app:/var/www/app
  nginx:
    image: 925336818186.dkr.ecr.eu-west-2.amazonaws.com/nginx:v2
    mem_limit: 200000000
    container_name: app_nginx
    ports:
        - "443:443"
    links:
        - workspace
    command: 'nginx'
